// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleControl.Data;

namespace VehicleControl.Migrations
{
    [DbContext(typeof(VehicleControlContext))]
    [Migration("20200817043426_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VehicleControl.Models.Anuncio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Combustivel");

                    b.Property<string>("Cor");

                    b.Property<DateTime>("DataVenda");

                    b.Property<int?>("Marcaid");

                    b.Property<int?>("Modeloid");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.HasKey("id");

                    b.HasIndex("Marcaid");

                    b.HasIndex("Modeloid");

                    b.ToTable("Anuncio");
                });

            modelBuilder.Entity("VehicleControl.Models.Marca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("VehicleControl.Models.Modelo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detalhe");

                    b.Property<int?>("Marcaid");

                    b.HasKey("id");

                    b.HasIndex("Marcaid");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("VehicleControl.Models.Anuncio", b =>
                {
                    b.HasOne("VehicleControl.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("Marcaid");

                    b.HasOne("VehicleControl.Models.Modelo", "Modelo")
                        .WithMany("Anuncios")
                        .HasForeignKey("Modeloid");
                });

            modelBuilder.Entity("VehicleControl.Models.Modelo", b =>
                {
                    b.HasOne("VehicleControl.Models.Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("Marcaid");
                });
#pragma warning restore 612, 618
        }
    }
}
